export const USER_LOADED = 'USER_LOADED'
export const USER_UPDATE = 'USER_UPDATE'
export const USER_LOADING = 'USER_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const CLEAR_ERROR = 'CLEAR_ERROR'

export const PLAYERS_LOADED = 'PLAYERS_LOADED'
export const LOAD_PLAYERS_ERROR = 'LOAD_PLAYERS_ERROR'
export const SORT_PLAYERS = 'SORT_PLAYERS'
export const FILTER = 'FILTER'
export const SHOW_SQUAD_PLAYER = 'SHOW_SQUAD_PLAYER'
export const SHOW_LIST_PLAYER = 'SHOW_LIST_PLAYER'

export const SHORTLIST_LOADED = 'SHORTLIST_LOADED'
export const SHORTLIST_ADD = 'SHORTLIST_ADD'
export const SHORTLIST_REMOVE = 'SHORTLIST_REMOVE'
export const SORT_SHORTLIST = 'SORT_SHORTLIST'
export const SHORTLIST_ERROR = 'SHORTLIST_ERROR'

export const SQUAD_PLAYERS_LOADED = 'SQUAD_PLAYERS_LOADED'
export const SQUAD_PLAYERS_ERROR = 'SQUAD_PLAYERS_ERROR'
export const SORT_SQUAD = 'SORT_SQUAD'
export const SELL_SQUAD_PLAYER = 'SELL_SQUAD_PLAYER'

export const BID_PLAYER_STATUS = 'BID_PLAYER_STATUS'
export const BID_ERROR = 'BID_ERROR'


